Whittle down the example a bit.
Bad news: I couldn't decouple this from circe/shapeless in
finite time.

Good news: I've patched scalac to be more selective about
when to disacard macro expansions in the presentation compiler.

```
⚡ sbt ++2.12.2 compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from /Users/jz/.sbt/0.13/plugins
[info] Loading project definition from /Users/jz/code/t9716/project
[info] Set current project to t9716 (in build file:/Users/jz/code/t9716/)
[info] Setting version to 2.12.2
[info] Reapplying settings...
[info] Set current project to t9716 (in build file:/Users/jz/code/t9716/)
[info] Updating {file:/Users/jz/code/t9716/}t9716...
[info] Updating {file:/Users/jz/code/t9716/}macros...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-compiler;2.12.2 ...
[info] Updating {file:/Users/jz/code/t9716/}client...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
[info] Compiling 1 Scala source to /Users/jz/code/t9716/macros/target/scala-2.12/classes...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/jz/code/t9716/client/target/scala-2.12/classes...
[error] /Users/jz/code/t9716/client/src/main/scala/sample/Client.scala:10: could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[sample.User]
[error]   deriveDecoder[User]
[error]                ^
[error] one error found
[error] (client/compile:compileIncremental) Compilation failed
[error] Total time: 5 s, completed 07/06/2017 4:20:00 PM
/code/t9716 on master*
⚡ sbt ++2.12.2-bin-5ce5b64-SNAPSHOT compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from /Users/jz/.sbt/0.13/plugins
[info] Loading project definition from /Users/jz/code/t9716/project
[info] Set current project to t9716 (in build file:/Users/jz/code/t9716/)
[info] Setting version to 2.12.2-bin-5ce5b64-SNAPSHOT
[info] Reapplying settings...
[info] Set current project to t9716 (in build file:/Users/jz/code/t9716/)
[info] Updating {file:/Users/jz/code/t9716/}macros...
[info] Updating {file:/Users/jz/code/t9716/}t9716...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-library;2.12.2-bin-5ce5b64-SNAPSHOT ...
[info] Updating {file:/Users/jz/code/t9716/}client...
[info] Compiling 1 Scala source to /Users/jz/code/t9716/macros/target/scala-2.12/classes...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/jz/code/t9716/client/target/scala-2.12/classes...
[success] Total time: 36 s, completed 07/06/2017 4:20:44 PM
```